import { CSSEffect, ScaleOpacityEffect } from 'scroll-parallax';

export const ALL_PARALLAX_PROPS = [
  { speed: 10 },
  { translateX: [-100, 100] as CSSEffect },
  { translateY: [-100, 100] as CSSEffect },
  { rotate: ['0turn', '1turn'] as CSSEffect },
  { rotateX: ['0turn', '1turn'] as CSSEffect },
  { rotateY: ['0turn', '1turn'] as CSSEffect },
  { rotateZ: ['0turn', '1turn'] as CSSEffect },
  { scale: [0, 1] as ScaleOpacityEffect },
  { scaleX: [0, 1] as ScaleOpacityEffect },
  { scaleY: [0, 1] as ScaleOpacityEffect },
  { scaleZ: [0, 1] as ScaleOpacityEffect },
  { opacity: [0, 1] as ScaleOpacityEffect },
  { disabled: true },
  { shouldAlwaysCompleteAnimation: true },
  { shouldDisableScalingTranslations: true },
  { easing: 'cubic-bezier(0.55, 0.085, 0.68, 0.53)' },
  { easing: 'cubic-bezier(0.2, -0.6, 1, -0.6)' },
  { startScroll: 0, endScroll: 1000 },
  { onChange: () => {} },
  { onProgressChange: () => {} },
  { targetElement: document.createElement('div') },
];
