name: Deploy Storybook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook

      - name: Install Surge
        run: npm install --global surge

      - name: Surge deploy
        run: surge ./storybook-static react-scroll-parallax-v3.surge.sh --token ${{ secrets.SURGE_TOKEN }}
