name: Deploy Storybook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Install Surge
        run: npm install --global surge

      - name: Surge deploy
        run: surge ./storybook-static react-scroll-parallax-v3.surge.sh --token ${{ secrets.SURGE_TOKEN }}
